kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: binding1
  namespace: default
subjects:
- kind: User
  name: user2
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

