kind: PersistentVolume

apiVersion: v1
metadata:
    name: pv0001
    labels:
         type: gluster
spec:
    capacity:
        storage: 15Gi
    accessModes:
        - ReadWriteOnce
    glusterfs:
        endpoints: "glusterfs-cluster"
        path: "/vol1"
        readOnly: false

---

kind: PersistentVolume

apiVersion: v1
metadata:
    name: pv0002
    labels:
         type: gluster
spec:
    capacity:
        storage: 15Gi
    accessModes:
        - ReadWriteOnce
    glusterfs:
        endpoints: "glusterfs-cluster"
        path: "/vol2"
        readOnly: false

---

kind: PersistentVolume

apiVersion: v1
metadata:
    name: pv0003
    labels:
         type: gluster
spec:
    capacity:
        storage: 15Gi
    accessModes:
        - ReadWriteOnce
    glusterfs:
        endpoints: "glusterfs-cluster"
        path: "/vol3"
        readOnly: false
